---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers

- name: configuration
  hosts: all
  become: true
  tasks:
  - name: enable repos
    template:
      src: ./open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- name: deploy haproxy
  hosts: frontends
  become: true
  roles:
   - haproxy

- name: deploy tomcat
  hosts: apps
  become: true
  roles:
   - tomcat

- name: deploy postgres
  become: true
  hosts: appdbs
  roles:
   - postgres

- name: deploy apache
  hosts: apps
  become: true
  roles:
   - apache